sudo: required
services:
  - docker

before_install:
  - docker build -t miikakan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true miikakan/react-test npm test -- --coverage

after_success:
  - docker build -t miikakan/multi-client ./client
  - docker build -t miikakan/multi-nginx ./nginx
  - docker build -t miikakan/multi-server ./server
  - docker build -t miikakan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push miikakan/multi-client
  - docker push miikakan/multi-nginx
  - docker push miikakan/multi-server
  - docker push miikakan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-273014965615
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
